name: post tweet everyday
on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    environment: myenvironment
    steps:
      - name: Create `.env` File
        uses: SpicyPizza/create-envfile@1.1
        with:
          file_name: .env
          envkey_API_KEY: ${{secrets.API_KEY}}
          envkey_API_SECRET_KEY: ${{secrets.API_SECRET_KEY}}
          envkey_ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          envkey_ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}


      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Pull the bot image
        run: docker pull ghcr.io/flaviodev27/bot-bandejao-uerj-v2/bot-bandejao-uerj-v2:latest

      - name: Run the bot image
        run: docker run --env-file .env ghcr.io/flaviodev27/bot-bandejao-uerj-v2/bot-bandejao-uerj-v2:latest

