name: run bot script without docker
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    environment: myenvironment
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.2
        with:
          envkey_API_KEY: ${{secrets.API_KEY}}
          envkey_API_SECRET_KEY: ${{secrets.API_SECRET_KEY}}
          envkey_ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          envkey_ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
          file_name: .env

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Run php script
        run: php main.php

